[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  [functions.generateTest]
    timeout = 240
  [functions.gradeTest]
    timeout = 60
  [functions.saveQuizResult]
    timeout = 30
